import { ServiceRequest, Technician } from './types';

export const INITIAL_TECHNICIANS: Technician[] = [
  {
    id: 1,
    name: 'Ramesh Kumar',
    phone: '9876543210',
    specialty: 'Laptop & Computer Repair',
    status: 'AVAILABLE',
    hourlyRate: 45.0,
  },
  {
    id: 2,
    name: 'Anita Sharma',
    phone: '9876543211',
    specialty: 'Smartphone & Tablet Repair',
    status: 'ON_JOB',
    hourlyRate: 40.0,
  },
  {
    id: 3,
    name: 'Vikram Singh',
    phone: '9876543212',
    specialty: 'AC & Refrigerator Repair',
    status: 'AVAILABLE',
    hourlyRate: 55.0,
  },
  {
    id: 4,
    name: 'Suresh Verma',
    phone: '9876543213',
    specialty: 'Washing Machine & Appliances',
    status: 'AVAILABLE',
    hourlyRate: 50.0,
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: 1,
    requestId: 'REQ-1001',
    customerName: 'Rahul Verma',
    customerPhone: '9811223344',
    customerEmail: 'rahul@example.com',
    serviceAddress: 'Flat 402, Sunshine Apts, Sector 14',
    deviceType: 'Laptop',
    brandModel: 'Dell Inspiron 15',
    problemDescription: 'Screen flickering and battery draining fast within 20 minutes.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    technicianId: 1,
    technicianName: 'Ramesh Kumar',
    estimatedCost: 65.0,
    actualCost: null,
    createdAt: '2026-10-04T08:00:00Z',
    updatedAt: '2026-10-04T09:30:00Z',
    resolutionNotes: 'Replacement battery ordered. Display connector reseated.',
  },
  {
    id: 2,
    requestId: 'REQ-1002',
    customerName: 'Priya Patel',
    customerPhone: '9822334455',
    customerEmail: 'priya@example.com',
    serviceAddress: 'House 12, Green Park',
    deviceType: 'Smartphone',
    brandModel: 'Samsung Galaxy S21',
    problemDescription: 'Charging port loose, device only charges when cable is held at an angle.',
    priority: 'MEDIUM',
    status: 'ASSIGNED',
    technicianId: 2,
    technicianName: 'Anita Sharma',
    estimatedCost: 35.0,
    actualCost: null,
    createdAt: '2026-10-03T14:30:00Z',
    updatedAt: '2026-10-04T07:15:00Z',
    resolutionNotes: 'Assigned to Anita Sharma for USB-C dock flex cable replacement.',
  },
  {
    id: 3,
    requestId: 'REQ-1003',
    customerName: 'Amit Joshi',
    customerPhone: '9833445566',
    customerEmail: 'amit@example.com',
    serviceAddress: 'Shop 5, Main Market',
    deviceType: 'AC',
    brandModel: 'Voltas 1.5 Ton Split AC',
    problemDescription: 'Compressor starting with humming sound but no cold air blowing.',
    priority: 'EMERGENCY',
    status: 'PENDING',
    technicianId: null,
    technicianName: null,
    estimatedCost: 80.0,
    actualCost: null,
    createdAt: '2026-10-04T06:00:00Z',
    updatedAt: '2026-10-04T06:00:00Z',
  },
  {
    id: 4,
    requestId: 'REQ-1004',
    customerName: 'Sunita Reddy',
    customerPhone: '9844556677',
    customerEmail: 'sunita@example.com',
    serviceAddress: 'B-104, Royal Palms',
    deviceType: 'Washing Machine',
    brandModel: 'LG Front Load 7kg',
    problemDescription: 'Drum not spinning during rinse cycle, showing error code dE.',
    priority: 'LOW',
    status: 'COMPLETED',
    technicianId: 4,
    technicianName: 'Suresh Verma',
    estimatedCost: 50.0,
    actualCost: 48.0,
    createdAt: '2026-10-01T10:00:00Z',
    updatedAt: '2026-10-02T15:20:00Z',
    resolutionNotes: 'Replaced door safety lock switch and tested 2 complete rinse & spin cycles.',
  },
];
